services:

  # Web Server Service
  product_nginx:
    image: nginx:alpine
    container_name: product_nginx
    ports:
      - "6060:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - product_app
      - product_db

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  product_db:
    image: postgres
    container_name: product_postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5466:5432"
    environment:
      POSTGRES_DB: Product
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  # Application Service
  product_app:
    container_name: product_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  product_pgadmin:
    image: dpage/pgadmin4
    container_name: product_pgadmin
    ports:
      - "5050:80"
    depends_on:
      - product_db
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
